name: Deploy to rundgang-frontend-23.dev.medienhaus.udk-berlin.de

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    concurrency: 
      group: ${{ github.ref }}
      cancel-in-progress: true

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Sync files to remote host
        uses: up9cloud/action-rsync@v1.1
        env:
          HOST: dev.medienhaus.udk-berlin.de
          KEY: ${{secrets.SSH_DEV_MEDIENHAUS_UDK_BERLIN_DE}}
          TARGET: /opt/rundgang-frontend-23/
          VERBOSE: true
          USER: root
          PORT: 22
          ARGS: --recursive --update --delete --compress --exclude=/.git/
          SSH_ARGS: '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
          SOURCE: .
      - name: Restart rundgang-frontend-23 service
        uses: fifsky/ssh-action@v0.0.5
        with:
          command: |
            cd /opt/rundgang-frontend-23/
            npm clean-install
            npm run build
            systemctl restart rundgang-frontend-23.service
          host: dev.medienhaus.udk-berlin.de
          user: root
          key: ${{secrets.SSH_DEV_MEDIENHAUS_UDK_BERLIN_DE}}