name: Deploy to rundgang.udk-berlin.de

on:
  workflow_dispatch:
    inputs:
      ref:
        description: The branch, tag or SHA to checkout
        required: true
        default: 'main'

jobs:
  deploy_prod:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.inputs.ref}}

      - name: Sync files to remote host
        uses: up9cloud/action-rsync@v1.1
        env:
          HOST: rundgang.udk-berlin.de
          KEY: ${{secrets.SSH_RUNDGANG_UDK_BERLIN_DE}}
          TARGET: /opt/rundgang-frontend-23/
          VERBOSE: true
          USER: root
          PORT: 22
          ARGS: --recursive --update --delete --compress --exclude=/.git/
          SSH_ARGS: '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
          SOURCE: .

      - name: Restart rundgang-frontend-23 service
        uses: fifsky/ssh-action@v0.0.5
        with:
          command: |
            cd /opt/rundgang-frontend-23/
            npm clean-install
            npm run build
            systemctl restart rundgang-frontend-23.service
          host: rundgang.udk-berlin.de
          user: root
          key: ${{secrets.SSH_RUNDGANG_UDK_BERLIN_DE}}
